version: '3.8'

services:
  node1:
    build: .
    ports:
      - "5001:5000"
    command: python3 app.py --port 5000

  node2:
    build: .
    ports:
      - "5002:5000"
    command: python3 app.py --port 5000

  node3:
    build: .
    ports:
      - "5003:5000"
    command: python3 app.py --port 5000